import cv2
import os
import time
import datetime
import csv
import numpy as np
from typing import List, Dict, Any
from hand_tracker import HandTracker
from trajectory_manager import TrajectoryManager

# Base directory for data
BASE_DATA_DIR = os.path.join("data", "raw")
# Supported classes: A-Z, a-z, and 0-9 (62 total)
# Canonical order: uppercase A-Z first, lowercase a-z second, digits 0-9 last.
# This order must match the label_mapping.json generated by preprocess.py.
VALID_LABELS = (
    [chr(i) for i in range(ord('A'), ord('Z') + 1)] +  # A-Z (26)
    [chr(i) for i in range(ord('a'), ord('z') + 1)] +  # a-z (26)
    [str(i) for i in range(10)]                         # 0-9 (10)
)


def get_folder_name(label: str) -> str:
    """
    Returns the Windows-safe filesystem folder name for a class label.
    Lowercase letters use a 'lc_' prefix to avoid collision with uppercase
    on case-insensitive filesystems (Windows NTFS).

    Examples:
        'a' -> 'lc_a'   (stored in data/raw/lc_a/)
        'A' -> 'A'       (stored in data/raw/A/)
        '5' -> '5'       (stored in data/raw/5/)
    """
    if label.isalpha() and label.islower():
        return f"lc_{label}"
    return label


def initialize_directories():
    """
    Ensures the dataset folder structure is set up.
    Creates data/raw/ and subfolders for A-Z, lc_a - lc_z (lowercase), and 0-9 (62 total).
    """
    os.makedirs(BASE_DATA_DIR, exist_ok=True)
    for label in VALID_LABELS:
        folder = get_folder_name(label)
        label_dir = os.path.join(BASE_DATA_DIR, folder)
        os.makedirs(label_dir, exist_ok=True)

def get_collection_stats() -> Dict[str, int]:
    """
    Scans the data directories and returns a dictionary with the count of
    NumPy (.npy) files for each valid class label.
    """
    stats = {}
    for label in VALID_LABELS:
        folder = get_folder_name(label)
        label_dir = os.path.join(BASE_DATA_DIR, folder)
        if os.path.exists(label_dir):
            # Count only .npy files
            count = len([f for f in os.listdir(label_dir) if f.endswith('.npy')])
            stats[label] = count
        else:
            stats[label] = 0
    return stats

def print_stats_console(stats: Dict[str, int]):
    """
    Prints a formatted summary and an ASCII bar-chart of the dataset counts to the console.
    """
    print("\n" + "="*50)
    print("           CURRENT DATASET STATISTICS           ")
    print("="*50)
    
    total_samples = sum(stats.values())
    
    # Print in columns for clean display
    cols = 4
    items = list(stats.items())
    for i in range(0, len(items), cols):
        row_str = "  ".join([f"{label}: {count:3d}" for label, count in items[i:i+cols]])
        print(row_str)
        
    print("-"*50)
    print(f" Total Samples Collected: {total_samples}")
    print("="*50 + "\n")

def draw_text_with_bg(img: cv2.Mat, 
                     text: str, 
                     position: tuple, 
                     font: int = cv2.FONT_HERSHEY_SIMPLEX, 
                     scale: float = 0.5, 
                     color: tuple = (255, 255, 255), 
                     thickness: int = 1, 
                     bg_color: tuple = (30, 30, 30), 
                     alpha: float = 0.7) -> cv2.Mat:
    """
    Renders text on the image frame with a semi-transparent background box.
    """
    (w, h), baseline = cv2.getTextSize(text, font, scale, thickness)
    x, y = position
    overlay = img.copy()
    cv2.rectangle(overlay, (x - 10, y - h - 10), (x + w + 10, y + baseline + 10), bg_color, -1)
    cv2.addWeighted(overlay, alpha, img, 1 - alpha, 0, img)
    cv2.putText(img, text, (x, y), font, scale, color, thickness, cv2.LINE_AA)
    return img

def run_collection_session(label: str):
    """
    Opens the webcam stream to collect samples for the specified label.
    """
    # Track statistics for the current session
    stats = get_collection_stats()
    label_count = stats.get(label, 0)
    total_count = sum(stats.values())

    tracker = HandTracker(
        max_num_hands=1,
        min_detection_confidence=0.7,
        min_tracking_confidence=0.7
    )
    trajectory = TrajectoryManager()
    
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open webcam.")
        return

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    # State variables
    recording = False
    recorded_points = []  # List of coordinates captured during the current recording
    
    # Snapshot freeze variables for visual confirmation
    confirm_freeze_until = 0.0
    confirm_frame = None

    p_time = 0
    hand_present_prev = False

    print(f"\n>>> Starting collection window for label '{label}'...")
    print(" Controls:")
    print("   [Space] : Start / Stop Recording")
    print("   [C / c] : Clear / Abort active drawing")
    print("   [Q / q] : Save & Return to Label Selection")
    print("=========================================================")

    while True:
        # Check if we are in visual confirmation freeze mode
        if time.time() < confirm_freeze_until:
            cv2.imshow("Air-Writing Dataset Collector", confirm_frame)
            # Short wait to avoid high CPU usage during freeze
            cv2.waitKey(10)
            continue

        success, frame = cap.read()
        if not success:
            print("Failed to read webcam frame.")
            break

        frame = cv2.flip(frame, 1)
        h, w, c = frame.shape

        # Hand landmark detection
        frame, hand_detected = tracker.find_hands(frame, draw=True)

        if hand_detected:
            landmarks = tracker.get_landmarks(frame, hand_idx=0)
            index_tip = tracker.get_landmark_by_id(landmarks, 8)
            
            if index_tip:
                px_x, px_y = index_tip["px_x"], index_tip["px_y"]
                norm_x, norm_y, norm_z = index_tip["x"], index_tip["y"], index_tip["z"]

                # Drawing current tracking point
                tip_color = (0, 0, 255) if recording else (0, 255, 0)
                cv2.circle(frame, (px_x, px_y), 8, tip_color, -1)

                if recording:
                    # Append coordinates to active storage
                    recorded_points.append([px_x, px_y, norm_x, norm_y, norm_z])
                    # Add to visualizer trajectory
                    trajectory.add_point(px_x, px_y, norm_x, norm_y, norm_z)
                else:
                    trajectory.trigger_new_stroke()

                # Coordinate display
                coord_text = f"X:{px_x:4d} Y:{px_y:4d} | Norm:({norm_x:.2f}, {norm_y:.2f}, {norm_z:.2f})"
                draw_text_with_bg(frame, coord_text, (20, h - 30), scale=0.55, color=(0, 255, 255))
            
            hand_present_prev = True
        else:
            if hand_present_prev:
                trajectory.trigger_new_stroke()
                hand_present_prev = False

        # Draw trajectory lines
        frame = trajectory.draw_trajectory(frame, color=(0, 0, 255), thickness=5)

        # FPS calculation
        c_time = time.time()
        fps = int(1 / (c_time - p_time)) if (c_time - p_time) > 0 else 0
        p_time = c_time

        # Render Head-Up Display (HUD)
        # Header bar
        cv2.rectangle(frame, (0, 0), (w, 45), (20, 20, 20), -1)
        cv2.putText(frame, f"DATASET COLLECTOR | TARGET LABEL: '{label}'", (20, 30), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)

        # Recording Status
        if recording:
            # Flashing record text based on millisecond clock
            if int(time.time() * 2) % 2 == 0:
                cv2.rectangle(frame, (w - 200, 10), (w - 20, 35), (0, 0, 255), -1)
                cv2.putText(frame, "● RECORDING", (w - 180, 28), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
        else:
            cv2.rectangle(frame, (w - 200, 10), (w - 20, 35), (100, 100, 100), -1)
            cv2.putText(frame, "STANDBY", (w - 160, 28), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)

        # Statistics overlays
        draw_text_with_bg(frame, f"FPS: {fps}", (20, 80), scale=0.5, color=(200, 250, 200))
        draw_text_with_bg(frame, f"Label '{label}' Samples: {label_count}", (20, 115), scale=0.5, color=(0, 255, 255))
        draw_text_with_bg(frame, f"Total Samples: {total_count}", (20, 150), scale=0.5, color=(255, 255, 200))
        if recording:
            draw_text_with_bg(frame, f"Recorded Frames: {len(recorded_points)}", (20, 185), scale=0.5, color=(100, 100, 255))

        # Bottom UI controls indicator
        controls_text = "[Space] Start/Stop Rec | [C] Clear Drawing | [Q] Return to Console"
        draw_text_with_bg(frame, controls_text, (w - 520, h - 30), scale=0.5, color=(220, 220, 220))

        # Display window
        cv2.imshow("Air-Writing Dataset Collector", frame)

        # Handle keyboard input
        key = cv2.waitKey(1) & 0xFF
        
        # Spacebar: Toggle recording status
        if key == 32:
            if not recording:
                # Start recording
                recording = True
                recorded_points = []
                trajectory.clear()
                print(">>> Recording started...")
            else:
                # Stop recording and process file saving
                recording = False
                print(f">>> Recording stopped. Captured {len(recorded_points)} frames.")
                
                if len(recorded_points) < 8:
                    print("⚠️ Warning: Sequence too short (under 8 frames). Discarded.")
                    trajectory.clear()
                    recorded_points = []
                else:
                    # Save files using Windows-safe folder name
                    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
                    folder = get_folder_name(label)
                    save_dir = os.path.join(BASE_DATA_DIR, folder)
                    
                    npy_path = os.path.join(save_dir, f"{label}_{timestamp}.npy")
                    csv_path = os.path.join(save_dir, f"{label}_{timestamp}.csv")
                    
                    # 1. Save NumPy file
                    np_array = np.array(recorded_points, dtype=np.float32)
                    np.save(npy_path, np_array)
                    
                    # 2. Save CSV file
                    with open(csv_path, mode='w', newline='') as f:
                        writer = csv.writer(f)
                        writer.writerow(["pixel_x", "pixel_y", "norm_x", "norm_y", "norm_z"])
                        writer.writerows(recorded_points)
                    
                    print(f"✓ Saved sample to: {npy_path}")
                    print(f"✓ Saved sample to: {csv_path}")

                    # Update statistics
                    label_count += 1
                    total_count += 1

                    # Setup Visual Confirmation Freeze Frame (1.0 second duration)
                    confirm_frame = frame.copy()
                    # Add graphical indicator overlay on freeze frame
                    cv2.rectangle(confirm_frame, (w // 2 - 200, h // 2 - 50), (w // 2 + 200, h // 2 + 50), (0, 150, 0), -1)
                    cv2.putText(confirm_frame, "SAMPLE SAVED!", (w // 2 - 130, h // 2 + 10), 
                                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 3, cv2.LINE_AA)
                    confirm_freeze_until = time.time() + 1.0
                    
                    # Reset active trajectory drawing canvas
                    trajectory.clear()
                    recorded_points = []

        # Clear / Abort active drawing
        elif key == ord('c') or key == ord('C'):
            recording = False
            trajectory.clear()
            recorded_points = []
            print("❌ Canvas cleared and recording aborted.")

        # Quit webcam session, returning to console prompt
        elif key == ord('q') or key == ord('Q'):
            print(">>> Closing capture window and returning to label selector.")
            break

    # Cleanup resources
    cap.release()
    cv2.destroyAllWindows()

def main():
    # Make sure subfolders are set up
    initialize_directories()
    
    print("=========================================================")
    print("        Air-Writing Dataset Collection System            ")
    print("=========================================================")
    
    while True:
        # Show collection stats before each input prompt
        stats = get_collection_stats() 
        print_stats_console(stats)
        
        # User input prompt for label selection
        # NOTE: Do NOT strip case — lowercase letters (a-z) are distinct classes from uppercase (A-Z).
        user_input = input(
            "Enter target label to collect\n"
            "  Uppercase letters : A-Z\n"
            "  Lowercase letters : a-z\n"
            "  Digits            : 0-9\n"
            "  Or type 'exit' to quit: "
        ).strip()
        
        if user_input.lower() in ['exit', 'quit']:
            print("Exiting Dataset Collection system. Goodbye!")
            break
            
        # Preserve case exactly — 'a' and 'A' are different classes
        target_label = user_input
        if target_label in VALID_LABELS:
            run_collection_session(target_label)
        else:
            print(f"⚠️ Invalid label '{user_input}'. Please enter A-Z (uppercase), a-z (lowercase), or 0-9.")

if __name__ == "__main__":
    main()
